when:
  - branch: [main]
    event: [manual, push]

variables:
  images:
    - &image_set_env bash:5.2.37
    - &image_plugin_buildkit gitea.vspdev.io/wci-plugins/buildkit:1.2.0
  global_env: &global_env
    VERSION: &VERSION 1.2.1
    ENV_FILE: &ENV_FILE envFile

steps:
  - name: set_dynamic_vars
    image: *image_set_env
    environment:
      <<: *global_env
    commands:
      - echo "IMAGE_TAG=latest" >> $ENV_FILE
      - echo "IMAGE_TAG_1=$VERSION" >> $ENV_FILE
      - cat $ENV_FILE
  - name: plugin_buildkit
    image: *image_plugin_buildkit
    backend_options:
      kubernetes:
        secrets:
          - name: gitea-registry
    settings:
      env-file: *ENV_FILE
      image-repo: gitea.vspdev.io
      image-name: vsp-dev/acme-nginx
      arch: linux/amd64,linux/arm64
