name: Renovate
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '15 04 * * *'
      timezone: "Europe/London"
permissions:
  contents: write
  pull-requests: write
jobs:
  renovate:
    name: Renovate run
    runs-on: docker
    container:
      image: cr.nulbit.io/nulbyte/actions-runner:1.0.7
      credentials:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    steps:
      - name: Run renovate bot
        uses: nulbyte/actions/renovatebot@main
        with:
          renovate_token: ${{ secrets.RENOVATE_TOKEN }}
          registry_user: ${{ secrets.RENOVATE_REGISTRY_USER }}
          registry_token: ${{ secrets.RENOVATE_REGISTRY_TOKEN }}
          gh_renovate_ro: ${{ secrets.GH_RENOVATE_RO }}
